
package com.axiastudio.pypapi.plugins.jente.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JFinanziariaService", targetNamespace = "http://infor.arezzo.it/jente/jfinanziaria/services", wsdlLocation = "http://jente-ws/jente/JFinanziariaServices?wsdl")
public class JFinanziariaService
    extends Service
{

    private final static URL JFINANZIARIASERVICE_WSDL_LOCATION;
    private final static WebServiceException JFINANZIARIASERVICE_EXCEPTION;
    private final static QName JFINANZIARIASERVICE_QNAME = new QName("http://infor.arezzo.it/jente/jfinanziaria/services", "JFinanziariaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://jente-ws/jente/JFinanziariaServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JFINANZIARIASERVICE_WSDL_LOCATION = url;
        JFINANZIARIASERVICE_EXCEPTION = e;
    }

    public JFinanziariaService() {
        super(__getWsdlLocation(), JFINANZIARIASERVICE_QNAME);
    }

    public JFinanziariaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JFINANZIARIASERVICE_QNAME, features);
    }

    public JFinanziariaService(URL wsdlLocation) {
        super(wsdlLocation, JFINANZIARIASERVICE_QNAME);
    }

    public JFinanziariaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JFINANZIARIASERVICE_QNAME, features);
    }

    public JFinanziariaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JFinanziariaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JFinanziariaServices
     */
    @WebEndpoint(name = "JFinanziariaPort")
    public JFinanziariaServices getJFinanziariaPort() {
        return super.getPort(new QName("http://infor.arezzo.it/jente/jfinanziaria/services", "JFinanziariaPort"), JFinanziariaServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JFinanziariaServices
     */
    @WebEndpoint(name = "JFinanziariaPort")
    public JFinanziariaServices getJFinanziariaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://infor.arezzo.it/jente/jfinanziaria/services", "JFinanziariaPort"), JFinanziariaServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JFINANZIARIASERVICE_EXCEPTION!= null) {
            throw JFINANZIARIASERVICE_EXCEPTION;
        }
        return JFINANZIARIASERVICE_WSDL_LOCATION;
    }

}
