
package com.axiastudio.pypapi.plugins.jente.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JFinanziariaServices", targetNamespace = "http://infor.arezzo.it/jente/jfinanziaria/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JFinanziariaServices {


    /**
     * 
     * @param richiesta
     * @return
     *     returns com.axiastudio.pypapi.plugins.jente.webservices.RispostaGestioneProposte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gestioneProposte", targetNamespace = "http://infor.arezzo.it/jente/jfinanziaria/services", className = "com.axiastudio.pypapi.plugins.jente.webservices.GestioneProposte")
    @ResponseWrapper(localName = "gestioneProposteResponse", targetNamespace = "http://infor.arezzo.it/jente/jfinanziaria/services", className = "com.axiastudio.pypapi.plugins.jente.webservices.GestioneProposteResponse")
    public RispostaGestioneProposte gestioneProposte(
        @WebParam(name = "richiesta", targetNamespace = "")
        RichiestaGestioneProposte richiesta);

}
