
package it.arezzo.infor.jente.jfinanziaria.services;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "JFinanziariaService", targetNamespace = "http://infor.arezzo.it/jente/jfinanziaria/services", wsdlLocation = "http://192.168.90.4/jente/JFinanziariaServices?wsdl")
public class JFinanziariaService
    extends Service
{

    private final static URL JFINANZIARIASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.arezzo.infor.jente.jfinanziaria.services.JFinanziariaService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.arezzo.infor.jente.jfinanziaria.services.JFinanziariaService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.90.4/jente/JFinanziariaServices?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.90.4/jente/JFinanziariaServices?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        JFINANZIARIASERVICE_WSDL_LOCATION = url;
    }

    public JFinanziariaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JFinanziariaService() {
        super(JFINANZIARIASERVICE_WSDL_LOCATION, new QName("http://infor.arezzo.it/jente/jfinanziaria/services", "JFinanziariaService"));
    }

    /**
     * 
     * @return
     *     returns JFinanziariaServices
     */
    @WebEndpoint(name = "JFinanziariaPort")
    public JFinanziariaServices getJFinanziariaPort() {
        return super.getPort(new QName("http://infor.arezzo.it/jente/jfinanziaria/services", "JFinanziariaPort"), JFinanziariaServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JFinanziariaServices
     */
    @WebEndpoint(name = "JFinanziariaPort")
    public JFinanziariaServices getJFinanziariaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://infor.arezzo.it/jente/jfinanziaria/services", "JFinanziariaPort"), JFinanziariaServices.class, features);
    }

}
